[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }

[versions]

# commons-lang3 = "3.18.0"
# commons-collections4 = "4.5.0"
junit-bom = "5.13.4"

checkstyle = "10.12.5"
versions-plugin = "0.53.0"
lombok-plugin = "9.0.0-rc2"
shadow-plugin = "9.1.0"
sonarqube-plugin = "6.3.1.5724"

junit = "5.13.4"
## ⬆ = "6.0.0-M1"
## ⬆ = "6.0.0-M2"
## ⬆ = "6.0.0-RC1"
## ⬆ = "6.0.0-RC2"


[libraries]
picocli = "info.picocli:picocli:4.7.5"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.15.2"
jackson-dataformat-yaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.15.2"

commons-lang3 = "org.apache.commons:commons-lang3:3.18.0"
commons-collections4 = "org.apache.commons:commons-collections4:4.5.0"
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.9.4"